### ISSUE TITLE
Send image attachments?

### ISSUE THREAD

**Issue by 2xaronl** [klatka/nc-talk-bot-component#17]
Does this integration support the sending of image attachments to Nextcloud Talk?  I'm looking for something similar to how images are sent using the existing Telegram or Nextcloud app notify services.

**Comment by klatka** [comment]
Unfortunately not but I will have a look into it

**Comment by klatka** [comment]
Nextcloud Talk Bots currently cannot send files, see https://github.com/nextcloud/spreed/issues/10715

**Comment by bibberp** [comment]
Hans I think I tried what you said, in my home assistant instance I put the text you sent (adding in my own URLs) and it just sent the text exactly as I typed it in, is there something else I need to do?

**Comment by hans99** [comment]
Just saw this doesn't work in either of the mobile clients, I have only used this in the desktop client (MacOS). Don't know if this is a limitation or a bug.
Are you using mobile client? If so, is it possible for you to try a desktop client?
(Just to make sure, and then we can ask/report the developer of the mobile clients)

**Comment by bibberp** [comment]
I get this in the web gui 

“person spotted” is my alt text

<img width="255" alt="image" src="https://github.com/user-attachments/assets/8b3a8a08-d812-45cd-b17f-3d420bd7bf2f" />

**Comment by bibberp** [comment]
Sadly the mobile client misses out on a ton of functionally that the web client has

**Comment by hans99** [comment]
Also uses this for camera snapshots, didn't test in mobile app until all worked in web-client :(

You need to give access to the image-files from NC to HA - I found that a much/unsecure - so I used markup like:
![image](data:image/jpeg;base64,{{ snapshot-in-base64 }})
Still don't work in mobile app though :(

Have no idea if it's possible to get something implemented in the mobile app, do you?

**Comment by hans99** [comment]
Nah, don't think this is doable for the mobile app. I can not see any support for the image-tag, and as @klatka stated above the bot can nog upload file. So for mobile app using the link-tag and make the image "public" from Home Assistant would be the only way, and then "click" it to see.

**Comment by phdelodder** [comment]
@hans99 did you had any luck using the markdown and base64 for posting images?

**Comment by hans99** [comment]
> [@hans99](https://github.com/hans99) did you had any luck using the markdown and base64 for posting images?

It works for the web/desktop client, but not for the phone app (using apple).

**Comment by phdelodder** [comment]
@hans99 could you please share an example?

**Comment by hans99** [comment]
For sure, this is what I am using:

A python shell script:
```
#!/usr/local/bin/python
import requests, base64, sys
response = requests.get(
    "http://localhost:8123/api/unifiprotect/thumbnail/{}/{}".format(sys.argv[1], sys.argv[2]),
    headers={
        "Authorization": "Bearer [Long lived token from Home Assistant]",
        "content-type": "application/json",
    },
)
response.encoding = 'utf-8'
print(base64.b64encode(response.content).decode('utf-8'))
```
Home Assistant configuration, for above script:
```
shell_command:
  unifiprotect_thumbnail: /config/scripts/unifiprotect_thumbnail.py {{ entity_id }} {{ event_id }}
```
And an automation:
```
alias: NC Bot Person Detected
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.[your camera motion detection]
    from: "on"
    to: "off"
    enabled: true
    alias: Detections
conditions: []
actions:
  - sequence:
      - action: shell_command.unifiprotect_thumbnail
        metadata: {}
        data:
          entity_id: "{{ config_entry_id(trigger.entity_id) }}"
          event_id: "{{ trigger.from_state.attributes.event_id }}"
        response_variable: thumb
      - action: notify.nctalkbot
        metadata: {}
        data:
          message: |-
            * Detection {{ trigger.from_state.attributes.friendly_name }}

                ![image](data:image/jpeg;base64,{{ thumb.stdout }})

            * At {{ this.attributes.last_triggered }}
mode: single
max_exceeded: silent
```

**Comment by phdelodder** [comment]
@hans99 thanks for the inspiration, I have come up with a workaround.

With some assistance from AI, I have made a script (https://gist.github.com/phdelodder/994fd201518fc9ff8cc668049903584c) that uploads using webdav and shares to a talk chat. It's a workaround, but it fits my needs

Shell command
```
upload_to_talk: /config/scripts/upload_to_talk.sh {{ file_path }} {{ talk_chat_id }} "{{ message }}"
```

Script for testing:
```
sequence:
  - alias: Take a Snapshot
    data:
      filename: /config/www/snapshots/doorbell.jpg
    target:
      entity_id: camera.doorbell
    action: camera.snapshot
  - action: shell_command.upload_to_talk
    data:
      file_path: /config/www/snapshots/doorbell.jpg
      talk_chat_id: 2b94bedt
      message: |-
        Detection Doorbell At {{ now().timestamp() | timestamp_custom('%I:%M %p - %b %d, %Y') }}
````
